AWSTemplateFormatVersion: '2010-09-09'
Description: 'API Gateway with Lambda backend for contact form submissions'

Parameters:
  SesIdentityArn:
    Type: String
    Description: ARN of the validated SES domain/identity
    Default: ''
  
  ApiDomainName:
    Type: String
    Description: Domain name for API Gateway (e.g., mxintech.org)
    Default: 'mxintech.org'
  
  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for the domain
    Default: ''
    AllowedPattern: '^$|^Z[A-Z0-9]+$'

Resources:
  # DynamoDB Table for storing contact submissions
  ContactSubmissionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ContactSubmissions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TimeToLiveSpecification:
        Enabled: false
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  # IAM Role for Lambda function
  ContactFormLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ContactFormLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                Resource: !GetAtt ContactSubmissionsTable.Arn

  # SES policy attached only when SesIdentityArn is provided (empty Resource is invalid)
  ContactFormLambdaSESPolicy:
    Type: AWS::IAM::Policy
    Condition: HasSesIdentity
    Properties:
      PolicyName: SESAccess
      Roles:
        - !Ref ContactFormLambdaRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendRawEmail
            Resource: !Ref SesIdentityArn

  # Lambda function for handling contact form submissions
  ContactFormLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ContactFormHandler
      Runtime: python3.12
      Handler: index.lambda_handler
      Role: !GetAtt ContactFormLambdaRole.Arn
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME: !Ref ContactSubmissionsTable
          SES_IDENTITY_ARN: !Ref SesIdentityArn
      Code:
        ZipFile: |
          import json
          import os
          import boto3
          import uuid
          from datetime import datetime
          from botocore.exceptions import ClientError
          
          dynamodb = boto3.resource('dynamodb')
          ses = boto3.client('ses')
          
          def lambda_handler(event, context):
              try:
                  # Parse request body
                  if isinstance(event.get('body'), str):
                      body = json.loads(event['body'])
                  else:
                      body = event.get('body', {})
                  
                  # Extract form data
                  contact_type = body.get('contactType', '')
                  name = body.get('name', '').strip()
                  email = body.get('email', '').strip()
                  mobile = body.get('mobile', '').strip()
                  message = body.get('message', '').strip()
                  
                  # Validate required fields
                  if not all([name, email, mobile, message, contact_type]):
                      return {
                          'statusCode': 400,
                          'headers': {
                              'Content-Type': 'application/json',
                              'Access-Control-Allow-Origin': '*',
                              'Access-Control-Allow-Headers': 'Content-Type',
                              'Access-Control-Allow-Methods': 'POST,OPTIONS'
                          },
                          'body': json.dumps({
                              'error': 'Missing required fields',
                              'message': 'Please fill in all required fields.'
                          })
                      }
                  
                  # Validate email format
                  if '@' not in email or '.' not in email.split('@')[1]:
                      return {
                          'statusCode': 400,
                          'headers': {
                              'Content-Type': 'application/json',
                              'Access-Control-Allow-Origin': '*',
                              'Access-Control-Allow-Headers': 'Content-Type',
                              'Access-Control-Allow-Methods': 'POST,OPTIONS'
                          },
                          'body': json.dumps({
                              'error': 'Invalid email format',
                              'message': 'Please provide a valid email address.'
                          })
                      }
                  
                  # Generate unique ID and timestamp
                  submission_id = str(uuid.uuid4())
                  timestamp = datetime.utcnow().isoformat() + 'Z'
                  
                  # Store in DynamoDB
                  table = dynamodb.Table(os.environ['TABLE_NAME'])
                  table.put_item(
                      Item={
                          'id': submission_id,
                          'contactType': contact_type,
                          'name': name,
                          'email': email,
                          'mobile': mobile,
                          'message': message,
                          'timestamp': timestamp
                      }
                  )
                  
                  # Send confirmation email via SES
                  ses_identity = os.environ.get('SES_IDENTITY_ARN', '')
                  if ses_identity:
                      try:
                          # Determine sender email from SES identity ARN or use default
                          sender_email = 'noreply@mxintech.org'
                          if 'identity/' in ses_identity:
                              # Extract domain from ARN if possible
                              pass
                          
                          # Email subject based on contact type
                          type_names = {
                              'member': 'Miembro',
                              'leader': 'Líder',
                              'speaker': 'Speaker',
                              'business': 'Patrocinador'
                          }
                          type_name = type_names.get(contact_type, 'Contacto')
                          
                          subject = f'Confirmación: Solicitud recibida - {type_name}'
                          
                          email_body = f"""
                          Hola {name},
                          
                          Gracias por contactarnos. Hemos recibido tu solicitud para {type_name.lower()} en México in Tech.
                          
                          Nos pondremos en contacto contigo pronto.
                          
                          Detalles de tu solicitud:
                          - Tipo: {type_name}
                          - Email: {email}
                          - Teléfono: {mobile}
                          
                          Mensaje:
                          {message}
                          
                          Saludos,
                          El equipo de México in Tech
                          """
                          
                          ses.send_email(
                              Source=sender_email,
                              Destination={'ToAddresses': [email]},
                              Message={
                                  'Subject': {'Data': subject, 'Charset': 'UTF-8'},
                                  'Body': {'Text': {'Data': email_body, 'Charset': 'UTF-8'}}
                              }
                          )
                      except ClientError as e:
                          # Log error but don't fail the request
                          print(f'SES error: {str(e)}')
                  
                  # Return success response
                  return {
                      'statusCode': 200,
                      'headers': {
                          'Content-Type': 'application/json',
                          'Access-Control-Allow-Origin': '*',
                          'Access-Control-Allow-Headers': 'Content-Type',
                          'Access-Control-Allow-Methods': 'POST,OPTIONS'
                      },
                      'body': json.dumps({
                          'success': True,
                          'message': 'Form submitted successfully',
                          'id': submission_id
                      })
                  }
                  
              except Exception as e:
                  print(f'Error: {str(e)}')
                  return {
                      'statusCode': 500,
                      'headers': {
                          'Content-Type': 'application/json',
                          'Access-Control-Allow-Origin': '*',
                          'Access-Control-Allow-Headers': 'Content-Type',
                          'Access-Control-Allow-Methods': 'POST,OPTIONS'
                      },
                      'body': json.dumps({
                          'error': 'Internal server error',
                          'message': 'An error occurred processing your request.'
                      })
                  }

  # API Gateway REST API
  ContactFormApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: ContactFormAPI
      Description: API for contact form submissions
      EndpointConfiguration:
        Types:
          - REGIONAL

  # API Gateway Resource
  ContactResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ContactFormApi
      ParentId: !GetAtt ContactFormApi.RootResourceId
      PathPart: contact

  # OPTIONS method for CORS preflight
  ContactOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ContactFormApi
      ResourceId: !Ref ContactResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true

  # POST method for form submissions
  ContactPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ContactFormApi
      ResourceId: !Ref ContactResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ContactFormLambda.Arn}/invocations'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  # Lambda permission for API Gateway
  ContactFormLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ContactFormLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ContactFormApi}/*/*'

  # API Gateway Deployment
  ContactFormApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ContactPostMethod
      - ContactOptionsMethod
    Properties:
      RestApiId: !Ref ContactFormApi
      StageName: prod

  # Custom Domain (conditional)
  ApiGatewayDomain:
    Type: AWS::ApiGateway::DomainName
    Condition: HasHostedZone
    Properties:
      DomainName: !Sub 'api.${ApiDomainName}'
      RegionalCertificateArn: !Ref ApiCertificate
      SecurityPolicy: TLS_1_2
      EndpointConfiguration:
        Types:
          - REGIONAL

  # ACM Certificate (if domain is provided)
  ApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: HasHostedZone
    Properties:
      DomainName: !Sub 'api.${ApiDomainName}'
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub 'api.${ApiDomainName}'
          HostedZoneId: !Ref HostedZoneId

  # API Gateway Base Path Mapping
  ApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Condition: HasHostedZone
    DependsOn:
      - ContactFormApiDeployment
      - ApiGatewayDomain
    Properties:
      DomainName: !Ref ApiGatewayDomain
      RestApiId: !Ref ContactFormApi
      Stage: prod

  # Route53 Record (if hosted zone provided)
  ApiRoute53Record:
    Type: AWS::Route53::RecordSet
    Condition: HasHostedZone
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub 'api.${ApiDomainName}'
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApiGatewayDomain.RegionalDomainName
        HostedZoneId: !GetAtt ApiGatewayDomain.RegionalHostedZoneId

Conditions:
  HasHostedZone: !Not [!Equals [!Ref HostedZoneId, '']]
  HasSesIdentity: !Not [!Equals [!Ref SesIdentityArn, '']]

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ContactFormApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Export:
      Name: !Sub '${AWS::StackName}-ApiEndpoint'
  
  ApiCustomDomain:
    Condition: HasHostedZone
    Description: API Gateway custom domain URL (base only; app appends /contact)
    Value: !Sub 'https://api.${ApiDomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-ApiCustomDomain'
  
  DynamoDBTableName:
    Description: DynamoDB table name for contact submissions
    Value: !Ref ContactSubmissionsTable
    Export:
      Name: !Sub '${AWS::StackName}-DynamoDBTable'
  
  LambdaFunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt ContactFormLambda.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaArn'
